excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://sarimsakcayi.github.io
title: sarimsakcayial.com
tagline: sar&#305;msak çay&#305;
description: http://www.sarimsakcayial.com/ sar&#305;msak çay&#305; zay&#305;flat&#305;r inceltir ve kilo verdirir.
paginate: 5